events {
    worker_connections 1024;
}

http {
    upstream nestjs_backend {
        # Docker Compose จะ resolve 'nestjs' ไปยัง IP ของ container ทั้ง 3 ตัว
        # ที่ทำงานอยู่ภายใต้ service ชื่อ 'nestjs' โดยอัตโนมัติ
        server nestjs:3000;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://nestjs_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}